<?php
/**
 * @var \OpenSubscriptions\OpenSubscriptions\Block\Adminhtml\Services\Details\Tabs\Info $block
 */

// current service
$service = $block->getService();
// first order related to service, can be null
$firstOrder = $service->getFirstOrder();
// customer assigned to service
$customer = $service->getCustomer();
// connection used by service
$connection = $service->getConnection();
// service's product
$product = $service->getProduct();
// settings collection
$settings = $this->getServiceSettings();
try {
    // submodule instance
    $submodule = $service->getSubmoduleInstance();
} catch(\Exception $e){
    // eg. no submodule matching
    $submodule = null;
}
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Main Informations')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php echo $block->escapeHtml(__('Service # %1', $service->getServiceId())) ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <td><?php echo $block->escapeHtml(__('Fake ID')) ?></td>
                    <td style="text-align:left"><?php echo $service->getFakeId() ?></td>
                </tr>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Name')) ?></td>
                    <td style="text-align:left"><?php echo $service->getName() ?></td>
                </tr>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Creation Date')) ?></td>
                    <td style="text-align:left"><?php echo $service->getCreatedAt() ?></td>
                </tr>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Last Update Date')) ?></td>
                    <td style="text-align:left"><?php echo $service->getUpdatedAt() ?></td>
                </tr>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Expire At')) ?></td>
                    <td style="text-align:left"><?php echo $service->getExpireAt() ?> (no automation yet)</td>
                </tr>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Status')) ?></td>
                    <td style="text-align:left"><strong style="color:<?php echo $block->getStatusColor() ?>"><?php echo $service->getStatusLabel() ?></strong></td>
                </tr>
                <?php if ($firstOrder): ?>
                    <tr>
                        <td><?php echo $block->escapeHtml(__('Placed from IP')) ?></td>
                        <td style="text-align:left"><?php echo $block->escapeHtml($firstOrder->getRemoteIp()); echo $firstOrder->getXForwardedFor() ? ' (' . $block->escapeHtml($firstOrder->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Customer name')) ?></td>
                    <td style="text-align:left"><?php echo $customer->getFirstname() ?> <?php echo $customer->getLastname() ?></td>
                </tr>
                <tr>
                    <td><?php echo $block->escapeHtml(__('Customer email')) ?></td>
                    <td style="text-align:left">
                        <a href="<?php echo $block->getCustomerUrl(); ?>">
                            <?php echo $block->escapeHtml($customer->getEmail()) ?>
                        </a>
                    </td>
                </tr>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Open Subscriptions Info')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <td><?php echo $block->escapeHtml(__('Submodule')) ?></td>
                        <td style="text-align:left"><?php echo $block->escapeHtml($service->getSubmodule()) ?></td>
                        <?php // TODO: link to submodule details ?>
                    </tr>
                    <tr>
                        <td><?php echo $block->escapeHtml(__('Product')) ?></td>
                        <td style="text-align:left">
                            <a href="<?php echo $block->getProductUrl(); ?>">
                                <?php echo $block->escapeHtml($product->getName()) ?>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $block->escapeHtml(__('Connection')) ?></td>
                        <td style="text-align:left">
                            <a href="<?php echo $block->getConnectionUrl(); ?>">
                                <?php echo $block->escapeHtml($connection->getName()) ?>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $block->escapeHtml(__('External ID')) ?></td>
                        <td style="text-align:left">
                            <?php echo $block->escapeHtml($service->getExternalId()) ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $block->escapeHtml(__('Username')) ?></td>
                        <td style="text-align:left"><?php echo $block->escapeHtml($service->getUsername()) ?></td>
                        <?php // TODO: additional button to get and log activity ?>
                    </tr>
                    <tr>
                        <td><?php echo $block->escapeHtml(__('Password')) ?></td>
                        <td style="text-align:left"><?php echo substr($block->escapeHtml($service->getPassword()), 0, 5) ?>...</td>
                        <?php // TODO: additional button to get and log activity ?>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Submodule Commands')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php // TODO: DO NOT CREATE many command instances ?>

        <table class="admin__table-secondary order-information-table">
            <thead>
                <tr>
                    <th>Command</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($submodule && $submodule->getCreateCommand()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getFormAction('create') ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-primary" type="submit" title="Create">Create</button>
                            </form>
                        </td>
                        <td style="text-align:left">
                            <?php echo $submodule->getCreateCommand()->getHelp(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($submodule && $submodule->getResetCredentialsCommand()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getFormAction('reset-credentials') ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-secondary" type="submit" title="Reset Credentials">Reset Credentials</button>
                            </form>
                        </td>
                        <td style="text-align:left">
                            <?php echo $submodule->getResetCredentialsCommand()->getHelp(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($submodule && $submodule->getEnableCommand()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getFormAction('enable') ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-secondary" type="submit" title="Enable">Enable</button>
                            </form>
                        </td>
                        <td style="text-align:left">
                            <?php echo $submodule->getEnableCommand()->getHelp(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($submodule && $submodule->getDisableCommand()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getFormAction('disable') ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-default" type="submit" title="Disable">Disable</button>
                            </form>
                        </td>
                        <td style="text-align:left">
                            <?php echo $submodule->getDisableCommand()->getHelp(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($submodule && $submodule->getStatusCommand()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getFormAction('status') ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-default" type="submit" title="Status">Status</button>
                            </form>
                        </td>
                        <td style="text-align:left">
                            <?php echo $submodule->getStatusCommand()->getHelp(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($submodule && $submodule->getDeleteCommand()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getFormAction('delete') ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-tertiary" type="submit" title="Delete">Delete</button>
                            </form>
                        </td>
                        <td style="text-align:left">
                            <?php echo $submodule->getDeleteCommand()->getHelp(); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if (!$service->getIsCreated()): ?>
                    <tr>
                        <td style="text-align:left">
                            <form class="action-element" action="<?php echo $block->getDeleteAction() ?>" method="post">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button class="action-tertiary" type="submit" title="Delete">Delete Locally</button>
                            </form>
                        </td>
                        <td style="text-align:left">Delates service in Open Subscriptions only, while not created.</td>
                    </tr>
                <?php endif; ?>

                <?php if ($submodule): ?>
                    <?php foreach ($submodule->getAdditionalCommands() as $additionalCommand){ ?>
                        <tr>
                            <td style="text-align:left">
                                <form class="action-element" action="<?php echo $block->getFormAction($additionalCommand->getId()) ?>" method="post">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button class="action-tertiary" type="submit"><?php echo $additionalCommand->getName(); ?></button>
                                </form>
                            </td>
                            <td style="text-align:left">
                                <?php echo $additionalCommand->getHelp(); ?>
                            </td>
                        </tr>
                    <?php } ?>
                <?php endif; ?>
            </tbody>
        </table>
        <!-- action-primary action-secondary action-tertiary action-quaternary action-default action-close -->
        <?php // TODO: deleteConfirm ?>

        <div id="popup-modal" style="display:none;">
            <div class="messages"></div>
        </div>

        <script>
        require(['jquery','Magento_Ui/js/modal/modal'], function($, modal){
            var addMessageToModal = function(msg, success){
                var className = 'message message-success success';
                if (success === false){
                    className = 'message message-error error';
                } else if (success === null){
                    className = 'message message-warning warning';
                }
                $('#popup-modal').find('.messages').html('<div class="'+className+'">'+msg+'</div>');
            }
            $(document).ready(function($) {
                var modalOptions = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Command result',
                    buttons: [{
                        text: $.mage.__('Continue'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                $(".order-information-table form").each(function() {
                    var $form = $(this);
                    $form.submit(function(e) {
                        // show modal
                        addMessageToModal('Executing...', null);
                        var popup = modal(modalOptions, $('#popup-modal'));
                        $('#popup-modal').modal('openModal');

                        // execute command by ajax call
                        $.ajax({
                            type: "POST",
                            dataType: "json",
                            url: $form.attr('action'),
                            data: $form.serialize(),
                            success: function(data){
                                if (data.success === true) {
                                    addMessageToModal('Command successful', true);
                                } else if (typeof data.error !== 'undefined') {
                                    addMessageToModal('Error: ' + data.error, false);
                                } else {
                                    addMessageToModal('Error during command execution', false);
                                }
                            },
                            error: function(data){
                                addMessageToModal('Unknown error', false);
                            }
                        });

                        e.preventDefault();
                    });
                });
            });
        });
        </script>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Settings')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <table class="admin__table-secondary order-information-table">
            <?php foreach ($settings as $setting): ?>
                <tr>
                    <td style="text-align:left"><?php echo $setting->getName(); ?></td>
                    <td style="text-align:left"><?php echo $setting->getValue(); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</section>
